# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'realtime' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for realtime
pod 'Socket.IO-Client-Swift', '~> 13.0.0'
  target 'realtimeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'realtimeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
